targetNamespace: ''
parameters: {}
packages:
  - name: ai
    environment:
      DO_GENAI_API_KEY: ${DO_GENAI_API_KEY}
    actions:
      - name: resume-suggestions
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000
          memory: 256
      - name: interview-agent
        runtime: python:3.11
        web: true
        limits:
          timeout: 60000
          memory: 512
      - name: job-match
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000
          memory: 256
      - name: ats-analysis
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000
          memory: 256
      - name: resume-parser
        runtime: python:3.11
        web: true
        limits:
          timeout: 60000
          memory: 512
