targetNamespace: ''
parameters: {}
packages:
  - name: ai
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    actions:
      - name: resume-suggestions
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000
          memory: 256
      - name: interview-agent
        runtime: python:3.11
        web: true
        limits:
          timeout: 60000
          memory: 512
